language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy3"
install:
  - pip install -e .
  - pip install -r dev-requirements.txt
script: py.test --cov clinch --cov-report term-missing
deploy:
  provider: pypi
  user: enaeseth
  password:
    secure: KR6FBfURVrQLOOOEGirtjzrz05FmqlkVP2uJZ8I5MsFeTfWVnSDCffMaT8CCWR5eX/L/IitGgY/Xf1KRsL0jqf/W+SDxSDiU44MtajdDqWwuXgPKAzDjpvhyy1qn6d+bp5q1/rZv5bKDVvSnAh6CvZAQ1z04cuGqtFO0Hdss4g8=
  on:
    tags: true
    repo: enaeseth/clinch
